#!/usr/bin/env python3
"""Emit a single-run YAML for kappa / subgoal-value sweeps (puzzle or humanoidmaze)."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

PUZZLE = {
    'env_name': 'puzzle-3x3-play-v0',
    'train_epochs': 500,
    'log_every_n_epochs': 10,
    'save_every_n_epochs': 500,
    'eval_freq': 100,
    'horizon': 25,
    'plan_candidates': 1,
    'dynamics': {
        'max_goal_steps_from_env': True,
        'clip_path_to_goal': True,
        'subgoal_distribution': 'diag_gaussian',
        'subgoal_stochastic_loss': 'nll',
        'subgoal_num_samples': 4,
        'subgoal_goal_representation': 'phi',
        'subgoal_target_mode': 'displacement',
    },
    'critic_agent': {
        'action_chunk_horizon': 5,
        'discount': 0.995,
        'max_goal_steps_from_env': True,
        'clip_chunk_to_goal': True,
        'goal_representation': 'phi',
    },
    'actor': {'spi_beta': 1.0, 'spi_tau': 5.0},
}

HUMANOID = {
    'env_name': 'humanoidmaze-medium-navigate-v0',
    'train_epochs': 500,
    'log_every_n_epochs': 10,
    'save_every_n_epochs': 500,
    'eval_freq': 100,
    'horizon': 25,
    'plan_candidates': 1,
    'dynamics': {
        'max_goal_steps_from_env': True,
        'clip_path_to_goal': True,
        'subgoal_distribution': 'diag_gaussian',
        'subgoal_stochastic_loss': 'nll',
        'subgoal_num_samples': 4,
        'subgoal_goal_representation': 'phi',
    },
    'critic_agent': {
        'action_chunk_horizon': 5,
        'discount': 0.995,
        'max_goal_steps_from_env': True,
        'clip_chunk_to_goal': True,
        'goal_representation': 'phi',
    },
    'actor': {'spi_beta': 1.0, 'spi_tau': 5.0},
}


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument('--family', choices=('puzzle', 'humanoid'), required=True)
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--tag', type=str, required=True, help='Short id for run_group / filename.')
    p.add_argument('--kappa_b', type=float, required=True)
    p.add_argument('--kappa_d', type=float, required=True)
    p.add_argument('--subgoal_value_alpha', type=float, required=True)
    p.add_argument('--subgoal_value_gap_scale', type=float, required=True)
    args = p.parse_args()

    root = PUZZLE.copy() if args.family == 'puzzle' else HUMANOID.copy()
    root['run_group'] = f'sweep500_{args.family}_{args.tag}'

    d = dict(root['dynamics'])
    d['subgoal_value_alpha'] = float(args.subgoal_value_alpha)
    d['subgoal_value_gap_scale'] = float(args.subgoal_value_gap_scale)
    root['dynamics'] = d

    c = dict(root['critic_agent'])
    c['kappa_b'] = float(args.kappa_b)
    c['kappa_d'] = float(args.kappa_d)
    root['critic_agent'] = c

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(
            '# Auto-generated by scripts/write_sweep_run_yaml.py — do not hand-edit.\n'
            f'# family={args.family} kb={args.kappa_b} kd={args.kappa_d} '
            f'alpha={args.subgoal_value_alpha} gap={args.subgoal_value_gap_scale}\n'
        )
        yaml.safe_dump(root, f, sort_keys=False, default_flow_style=False)


if __name__ == '__main__':
    main()
